### ISSUE TITLE
non-random splitting the data inflated the correlation

### ISSUE THREAD

**Issue by liyupeng111** [pjsample/human_5utr_modeling#4]
modeling/training_MRL_CNN.ipynb

df.sort_values('total_reads', inplace=True, ascending=False)
df.reset_index(inplace=True, drop=True)
df = df.iloc[:280000]
e_test = df.iloc[:20000]
e_train = df.iloc[20000:]

The testing set has the highest 'total reads' values, which is not random splitting the data

If random splitting the data, the R^2 will decrease to ~0.88 (after removing UTRs with low 'total reads' using df = df.iloc[:280000]), or  ~0.73 (not removing UTRs with low 'total reads' using df = df.iloc[:280000] )

**Comment by pjsample** [comment]
Hi Yupeng,

Yes, that sounds like the expected outcomes of the splitting schemes you tested. The logic behind choosing UTRs with the highest sequencing depth for the test set is that their observed density across the polysome fractions is more likely to represent the true population density within the samples. Whereas UTRs with low sequencing counts will be noisier and more likely to differ significantly from their true distributions. Ultimately, our goal was to train a model that can predict what is going on within the cell. UTRs with high total reads will capture that better than sequences with low reads. With that in mind, we trained our model on noisy data and evaluated it with cleaner and biologically better represented data.

**Comment by liyupeng111** [comment]
Thanks for the clarification!
